config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get     'esci'  => 'sessions#esci', as: 'esci'
  post    'cercaservizi' =>'ricerches#servizivicini'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'servizis/:id/Aggpref'  => 'favorites#create', as: 'aggiungi'
  get    'favorites/:id/cancella' => 'favorites#destroy', as: 'cancellapreferiti'
  get    '/preferiti'          => 'users#listapreferiti', as: 'preferiti'
  get    '/domande/:id/cancella' => 'domandes#destroy', as: 'cancelladomande'
  get    '/risposte/:id/cancella' => 'rispostes#destroy', as: 'cancellarisposte'
  get    '/recensioni/:id/cancella' => 'recensionis#destroy', as: 'cancellarecensioni'
  get    '/servizi/:id/cancella'    => 'servizis#destroy', as: 'cancellaservizi'
  get    '/users/:id/cancella'      =>  'users#destroy', as: 'cancellautente'
  post    '/domanda/:id/vote_up'     => 'domandes#vote_up', as: 'vote_up_question'
  post    '/domanda/:id/vote_down'     => 'domandes#vote_down', as: 'vote_down_question'
  post    '/risposta/:id/vote_up'     => 'rispostes#vote_up', as: 'vote_up_answer'
  post    '/risposta/:id/vote_down'     => 'rispostes#vote_down', as: 'vote_down_answer'
  resources :users,                only: [:edit, :index, :update, :show, :new, :create]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :servizis,          only: [:create, :show]
  resources :recensionis,       only: [:create]
  resources :domandes,          only: [:create, :edit, :update, :show]
  resources :rispostes,          only: [:create, :edit, :update, :show]
  resources :ricerches,          only: [:create, :destroy]
  resource :session, only: [:create]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  #get /
  def home
    @user=currentuser
    @ricerche=Ricerche.new
    if !@user.nil?
      @servizi = currentuser.servizis.build if logged_in?
      @serviziutente = currentuser.feed.paginate(page: params[:page])
    end
  end
  def help
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>
>>>>>>> 649c4984393de629584660d4e50abe9c2dd7ce3a

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
   <% if logged_in? %>

   <head>
    <style>

          @import url('https://fonts.googleapis.com/css?family=Merriweather');
          h1{
	    color:#B22222;
          }

          #div01{
	    font-family: 'Merriweather', serif;
	    color: black;
          }

          #div02{
	    font-family: 'Merriweather', serif;
	    width: 500px;
	    margin: left;
	    border: 2px solid black;
	    color:black;
	    position: relative;
	    overflow: auto;
	    text-align: left;
	    padding: 10px 10px;
	    border-radius: 10px 10px 10px 10px;
          }

          #div03{
	    font-family: 'Merriweather', serif;
	    width: 900px;
	    margin: left;
	    border: 2px solid black;
	    color:black;
	    position: relative;
	    overflow: auto;
	    text-align: left;
	    padding: 10px 10px;
	    border-radius: 10px 10px 10px 10px;
          }

          #div04{
	    font-family: 'Merriweather', serif;
	    width: 500px;
	    margin: left;
	    border: 2px solid black;
	    position: relative;
	    overflow: auto;
	    text-align: left;
	    padding: 10px 10px;
	    border-radius: 10px 10px 10px 10px;
          }

          #bd{
	    color: black;
          }

          a:link, a:visited {
	    text-decoration: underline;
	   
	    background-color: transparent;
	  }

	  #cercavicino{
	    background: white;
	    border: none;       /* nessun bordo */
	    color: red;        /* colore del testo    */
	    font-weight: bold;  /* testo in grassetto  */
	    padding: 0;         /* padding             */
	    height: 25px;       /* altezza             */
	    width: 150px;        /* larghezza           */
	    border-radius: 10px 10px 10px 10px;
	  }

    </style>

   </head>

   <body id='bd' bgcolor=#A9A9A9>
      <div id='div01' class="row" align="left">
	<aside class="col-md-4">


	  <section class="user_info">
	    <%= render 'shared/user_info' %>
	  </section>

	  <br>

	  <div id='div02' align="left">
	    <b><center>Aggiungi un nuovo servizio</center></b>
	    <br>
	    <section class="servizi_form">
	      <%= render 'shared/servizi_form' %>
	    </section>
	  </div>

	</aside>

	<br>

	<div id='div03' class="col-md-8">
	  <h3>Servizi erogati:</h3>
	  <%= render 'shared/feed' %>
	</div>

	<br>

	<div class="col-md-8">
	  <%= link_to "Mostra preferiti", preferiti_path %>
	</div>

	<br>

	<div id='div04'>
	  <b><center>Cerca servizio</center></b>
	  <br>
	  <section class="ricerca_form">
	    <%= render 'shared/ricerche_form' %>
	  </section>
	</div>

      <br>

      <section class="Cercavicino">
	    <button id="cercavicino"> Cerca vicino a te </button>
	</section>
	<br>

	<div id="servizivicini">
	Servizi vicini:
	</div>
      <script>
      function initAutocomplete() {
	var indirizzi = document.getElementsByClassName('indirizzi');
	var indirizzo1=indirizzi[0];
	var indirizzo2=indirizzi[1];
	var cerca1 = new google.maps.places.Autocomplete(indirizzo1, {
	  types: ['geocode']
    });
      var cerca2= new google.maps.places.Autocomplete(indirizzo2, {
	  types: ['geocode']
    });
	cerca1.addListener('place_changed', function() {
	  var places1 = cerca1.getPlace();
	});
	cerca2.addListener('place_changed', function() {
	  var places2 = cerca2.getPlace();
	});
      }
      </script>
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCQIh8MGEehUptz2u7vr8JbRvyvB6mA4M8&libraries=places&callback=initAutocomplete"
	async defer></script>
      <script src="http://code.jquery.com/jquery-1.6.4.min.js" type="text/javascript"></script>
      <script type="text/javascript">
      $(document).ready(function(){
	$("#cercavicino").click(function(){
	  if (navigator.geolocation){
	    var position=navigator.geolocation.getCurrentPosition(function(position){
	    var lat = position.coords.latitude;
	    var long= position.coords.longitude;
	    $.ajax({
	      url: '/cercaservizi',
	      type: 'POST',
	      data:{
	      latitude: lat,
	      longitude: long
	      },
	      success: function(response) {
	      $("#servizivicini").html(response)
	    }
	  });
	});
	}
	});
      });
    </script>
</body>
  <% else %>


    <head>
        <title><%= yield(:title) %> | All Around You App</title>



        <style>
          @import url('https://fonts.googleapis.com/css?family=Merriweather');

          #par1{
            font-family: 'Merriweather', serif;
            font-size: 25px;
            color: black;

          }

          h2{
            font-family: 'Merriweather', serif;
            color: black;
          }
          
          #contatti{
            font-family: 'Merriweather', serif;
            color: black;
          }

          #par2{
            font-family: 'Merriweather', serif;
            font-size: 20px;
            color: black;
          }


           #par3{

            background-color:transparent;
            width:360px;
            height:80px;
            margin:0 auto;
            margin-top:50px;
            font-family:arial;color:black;
            text-align:center;
            border: black 2px solid;
            border-radius: 10px 10px 10px 10px;

          }

        </style>


    </head>
    <body bgcolor="#A9A9A9">
        <center>

          <div id="par1">
            <h1>All Around You</h1>
          </div>

        </center>
        <p>

	    <div id="par2">
	      <center>
		Con All Around You puoi trovare facilmente i servizi più vicini a te!
	      </center>
	    </div>

	    <br>

	     <div id = "par3">
      <p> <h2><%= link_to "Registrati!", signup_path, id: 'registrati' %></p></h2>
    </div>

    <div id = "par3">
	<p><h2><%= link_to "Loggati!", login_path, id: 'loggati' %></h2></p>
    </div>
    <div id ="par3">
	 <p><h2><%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path, id:'oauth' %></h2></p>
    </div>
    </p>
    <hr>
    <b id='contatti'>Contattaci alla e-mail: </b>allroundyou@gmail.com
    </body>
   <% end %>
</html>

app/views/static_pages/servizicercati.html.erb
<head>

  <style>
  
    @import url('https://fonts.googleapis.com/css?family=Merriweather');
   
    h1{
	color:#B22222;
	font-family: 'Merriweather', serif; 
    }
    
    div1{
      color: black;
      font-family: 'Merriweather', serif; 
    }
          
          
  </style>

</head>


<body bgcolor='#A9A9A9'>

    <h1> Servizi cercati: </h1>
    <div class="row-md-8" align="left">
	<% if @servizi.any? %>
	<div id='div1'>
	  <ol class="servizi">
	    <%= render @servizi %>
	  </ol>
	<div>
	<% end %>
    </div>

</body>