config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get     'esci'  => 'sessions#esci', as: 'esci'
  post    'cercaservizi' =>'ricerches#servizivicini'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'servizis/:id/Aggpref'  => 'favorites#create', as: 'aggiungi'
  get    'favorites/:id/cancella' => 'favorites#destroy', as: 'cancellapreferiti'
  get    '/preferiti'          => 'users#listapreferiti', as: 'preferiti'
  get    '/domande/:id/cancella' => 'domandes#destroy', as: 'cancelladomande'
  get    '/risposte/:id/cancella' => 'rispostes#destroy', as: 'cancellarisposte'
  get    '/recensioni/:id/cancella' => 'recensionis#destroy', as: 'cancellarecensioni'
  get    '/servizi/:id/cancella'    => 'servizis#destroy', as: 'cancellaservizi'
  get    '/users/:id/cancella'      =>  'users#destroy', as: 'cancellautente'
  post    '/domanda/:id/vote_up'     => 'domandes#vote_up', as: 'vote_up_question'
  post    '/domanda/:id/vote_down'     => 'domandes#vote_down', as: 'vote_down_question'
  post    '/risposta/:id/vote_up'     => 'rispostes#vote_up', as: 'vote_up_answer'
  post    '/risposta/:id/vote_down'     => 'rispostes#vote_down', as: 'vote_down_answer'
  resources :users,                only: [:edit, :index, :update, :show, :new, :create]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :servizis,          only: [:create, :show]
  resources :recensionis,       only: [:create]
  resources :domandes,          only: [:create, :edit, :update, :show]
  resources :rispostes,          only: [:create, :edit, :update, :show]
  resources :ricerches,          only: [:create, :destroy]
  resource :session, only: [:create]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/domande.rb
class Domande < ApplicationRecord
  attr_accessor :servizi_id # :vote_count, :likecount, :nolikecount
  belongs_to :user
  belongs_to :servizi
  has_many :rispostes
  default_scope -> { order(created_at: :desc) }
  validates :content, presence: true, length: { maximum: 250 }
end

app/controllers/domandes_controller.rb
class DomandesController < ApplicationController
    before_action :logged_in_users,   only: [:create, :destroy]
    before_action :userdomanda, only: [:destroy, :edit]
    def create
       session[:has_voted]=false
       session[:like]=false
       session[:dislike]=false
       @servizio=Servizi.find_by(id: params[:domande][:servizio_id])
       @domande=Domande.new
       @domande.content=params[:domande][:content]
       @domande.servizi=@servizio
       @domande.user=currentuser
       @domande.vote_count=0
       @domande.likecount=0
       @domande.nolikecount=0
       if @domande.save
          flash[:success]= "Domanda inserita con successo"
          redirect_to @servizio
       else
          @feed_items = []
          render 'static_pages/home'
       end
    end
    def destroy
       domanda=Domande.find(params[:id])
       redirect_to root_url if domanda.nil?
       @servizio=domanda.servizi
       domanda.destroy
       flash[:success] = "Domanda eliminata"
       redirect_to @servizio
    end
    #get domandes/:id
    def edit
      @domanda=Domande.find(params[:id])
    end
    #patch domandes/:id
    def update
       @domanda=Domande.find(params[:id])
       if @domanda.update_attributes(domande_params)
        flash[:success]="Domanda modificata"
        redirect_to @domanda.servizi
       else
        render 'edit'
      end
    end
    def show
        @domanda=Domande.find(params[:id])
        @risposte=Risposte.new
        @rispostes=@domanda.rispostes
    end
    def vote_up
        @domanda=Domande.find(params[:id])
         if !session[:has_voted] && !session[:dislike]
            @domanda.increment!(:vote_count)
            @domanda.increment!(:likecount)
            session[:has_voted]=true
            session[:like]=true
            redirect_to @domanda
            return true
        end
        if !session[:has_voted] && session[:dislike]
            @domanda.increment!(:likecount)
            @domanda.decrement!(:nolikecount)
            session[:has_voted]=true
            session[:like]=true
            redirect_to @domanda
            return true
        end
        if session[:has_voted] && !session[:dislike]
            @domanda.decrement!(:vote_count)
            @domanda.decrement!(:likecount)
            session[:like]=false
            session[:has_voted]=false
            redirect_to @domanda
            return true
        end
        if  session[:has_voted] && session[:dislike]
            @domanda.increment!(:likecount)
            @domanda.decrement!(:nolikecount)
            session[:like]=true
            session[:has_voted]=true
            session[:dislike]=false
            redirect_to @domanda
            return true
        end
        redirect_to @domanda
    end
    def vote_down
        @domanda=Domande.find(params[:id])
         if !session[:has_voted] && !session[:like]
            @domanda.increment!(:vote_count)
            @domanda.increment!(:nolikecount)
            session[:has_voted]=true
            session[:dislike]=true
            redirect_to @domanda
            return true
        end
        if !session[:has_voted] && session[:like]
            @domanda.increment!(:likecount)
            @domanda.decrement!(:nolikecount)
            session[:has_voted]=true
            session[:dislike]=true
            redirect_to @domanda
            return true
        end
        if session[:has_voted] && !session[:like]
            @domanda.decrement!(:vote_count)
            @domanda.decrement!(:nolikecount)
            session[:dislike]=false
            session[:has_voted]=false
            redirect_to @domanda
            return true
        end
        if  session[:has_voted] && session[:like]
            @domanda.increment!(:nolikecount)
            @domanda.decrement!(:likecount)
            session[:dislike]=true
            session[:has_voted]=true
            session[:like]=false
            redirect_to @domanda
            return true
        end
        redirect_to @domanda
    end
    private
    def domande_params
       params.require(:domande).permit(:content, :servizio_id)
    end
    def userdomanda
      @domanda = currentuser.domandes.find_by(id: params[:id])
      redirect_to root_url if @domanda.nil?
    end
    #aux method
    def nouserservizio(serv)
        if serv.user==currentuser
            flash[:danger] = "Domanda effettuata dall'utente creatore del servizio, errore"
            redirect_to serv
        end
    end
end

app/helpers/domandes_helper.rb
module DomandesHelper
end

app/views/domandes/_domande.html.erb
<li id="Domande-<%= domande.id %>">
  <span class="nome"><%= link_to "Visualizza domanda", domande_path(domande.id)%></span>
  <span class="nome"><%= link_to domande.user.name, domande.user%></span>
  <span class="nome"><%= link_to domande.servizi.nome, domande.servizi%></span>
  <span class="content"><%= domande.content %></span>
  <span class="modifica"><%= link_to 'Modifica', edit_domande_path %></span>
  <span class="timestamp">
  <% if currentuser==domande.user %>
      <%= link_to "Cancella", cancelladomande_path(domande.id) %>
    <% end %>
  </span>
</li>

app/views/domandes/edit.html.erb
<h1>Modifica domanda</h1>
<%= form_for(@domanda) do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Scrivi domanda" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/domandes/show.html.erb
<head>

  <style>
    @import url('https://fonts.googleapis.com/css?family=Merriweather');
    #like{
     font-family: 'Merriweather', serif;
     
    }
    #domanda{
    font-family: 'Merriweather', serif;
     font-family: 'Merriweather', serif;
	    width: 500px;
	    margin: left;
	    border: 2px solid black;
	    position: relative;
	    overflow: auto;
	    text-align: left;
	    padding: 10px 10px;
	    border-radius: 10px 10px 10px 10px;
    }
    
    #like{
       font-family: 'Merriweather', serif;
       display:inline;
    }
    #rispostacontent1{
      font-family: 'Merriweather', serif;
    }
    
    
  </style>

</head>


<body bgcolor="#A9A9A9">
      <br><br>
      <div id='domanda'>
      
      <ul id="Domande-<%= @domanda.id %>">
        <b>Domanda: </b><span class="content"><%= @domanda.content %></span>
        <br>
	<b>Posta da: </b><span class="nome"><%= link_to @domanda.user.name, @domanda.user%></span>
	<br>
	<b>Servizio: </b><span class="nome"><%= link_to @domanda.servizi.nome, @domanda.servizi %></span>
	<br>
	<span class="timestamp">
	</ul>
	
	
	<% if currentuser==@domanda.user %>
	<center><%= link_to "Cancella", cancelladomande_path(@domanda)%></center>
	<% end %>
	</div>
	
	<br>
	</span>
	  <br>
	  
	  
	  <div id='like'>
	  
	    <%= button_to "Mi piace", vote_up_question_path(@domanda) %>
	    <%= button_to "Non mi piace", vote_down_question_path(@domanda) %>
	    
	  </div>
	  
	  <hr>
	  
	  <div id='rispostacontent1'>
	    <h3>Numero Voti: (<%= @domanda.vote_count %>)</h3>
	  
	    <p> Mi piace: (<%= @domanda.likecount %>) </p>
	  
	    <p> Non mi piace: (<%= @domanda.nolikecount %>) </p>
	  
	<div class="row-md-8" align="left">
	  <% if @domanda.rispostes.any? %>
	    <h3>Numero Risposte: (<%= @domanda.rispostes.count %>)</h3>
	    <ol class="Risposte">
	      <%= render @rispostes %>
	    </ol>
	  <% end %>
	</div>
	<div class=row-md-8" align="left">
	  <%= form_for (@risposte) do |f| %>
	    <%=f.hidden_field 'domanda_id', :value => @domanda.id %>
	    <div class="field">
	      <%= f.text_area :content, id: 'rispostacontent', placeholder: "Scrivi risposta" %>
	  </div>
	    <%= f.submit "Manda Risposta", class: "btn btn-primary" %>
	</div>
	
	</div>
	<% end %>
      
</body>