config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get     'esci'  => 'sessions#esci', as: 'esci'
  post    'cercaservizi' =>'ricerches#servizivicini'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'servizis/:id/Aggpref'  => 'favorites#create', as: 'aggiungi'
  get    'favorites/:id/cancella' => 'favorites#destroy', as: 'cancellapreferiti'
  get    '/preferiti'          => 'users#listapreferiti', as: 'preferiti'
  get    '/domande/:id/cancella' => 'domandes#destroy', as: 'cancelladomande'
  get    '/risposte/:id/cancella' => 'rispostes#destroy', as: 'cancellarisposte'
  get    '/recensioni/:id/cancella' => 'recensionis#destroy', as: 'cancellarecensioni'
  get    '/servizi/:id/cancella'    => 'servizis#destroy', as: 'cancellaservizi'
  get    '/users/:id/cancella'      =>  'users#destroy', as: 'cancellautente'
  post    '/domanda/:id/vote_up'     => 'domandes#vote_up', as: 'vote_up_question'
  post    '/domanda/:id/vote_down'     => 'domandes#vote_down', as: 'vote_down_question'
  post    '/risposta/:id/vote_up'     => 'rispostes#vote_up', as: 'vote_up_answer'
  post    '/risposta/:id/vote_down'     => 'rispostes#vote_down', as: 'vote_down_answer'
  resources :users,                only: [:edit, :index, :update, :show, :new, :create]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :servizis,          only: [:create, :show]
  resources :recensionis,       only: [:create]
  resources :domandes,          only: [:create, :edit, :update, :show]
  resources :rispostes,          only: [:create, :edit, :update, :show]
  resources :ricerches,          only: [:create, :destroy]
  resource :session, only: [:create]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  devise :omniauthable, omniauth_providers: [:google_oauth2]
  has_many :servizis, dependent: :destroy #lol
  has_many :recensionis, dependent: :destroy
  has_many :domandes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :rispostes, dependent: :destroy
  attr_accessor :remember_token, :reset_token
  before_save { self.email = email.downcase }
  before_create { create_activation_digest }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
   has_secure_password

   validates :password, length: { minimum: 6 }, allow_blank: true
 def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  def self.from_omniauth(auth)
    data = auth["info"]
    user = User.where(email: data['email']).first
    if user
       user
    else
     userr=User.new
     userr.name=data['name']
     userr.email=data['email']
     userr.password = Devise.friendly_token[0,20]
     userr.save
     userr
     end
  end
  #Activation remember digest saved on db
  def create_activation_digest
    self.activation_token=User.nuovotoken
    self.activation_digest=User.digest(activation_token)
  end
  def feed
    Servizi.where("user_id = ?", id)
  end
  def preferiti
    Favorite.where("user_id = ?", self.id)
  end
  #Modifica reset password digest
  def create_reset_digest
    self.reset_token = User.nuovotoken
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end
  #Manda mail all'utente
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now!
  end
  #Cookie remember token
  def User.nuovotoken
      SecureRandom.urlsafe_base64
  end
  def remember
    self.remember_token = User.nuovotoken
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  def authenticated?(attribute,token)
      digest=self.send("#{attribute}_digest")
      return false if digest.nil?
      BCrypt::Password.new(digest).is_password?(token)
  end
  def forget
      update_attribute(:remember_digest, nil)
  end
  def paswscaduta?
    reset_sent_at < 2.hours.ago
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
     def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
       @user = User.from_omniauth(request.env['omniauth.auth'])
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        log_in(@user)
        redirect_to @user
   end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_users, only: [:edit, :index, :update, :destroy]
  before_action :userincorretto, only: [:edit, :update]
  before_action :seiadmin, only: :rendiadmin
  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(:page => params[:page], per_page: 15)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @servizi=@user.servizis.paginate(page: params[:page])
  end
  def listapreferiti
    cuser=currentuser
    @favorite=cuser.preferiti
  end
  # GET /users/new
  def new
    @user = User.new
  end
  def userincorretto
    @user=User.find(params[:id])
    if @user!=currentuser
       reindirizza(@user)
    end
  end
  def seiadmin
    return currentuser.admin?
  end
  # GET /users/1/edit
  def edit
    @user=User.find(params[:id])
  end
  def rendiadmin
    @user=User.find_by(id: params[:id])
    @user.admin=true
  end
  # POST /users
  # POST /users.json
    def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.account_activation(@user).deliver_now!
      flash[:info] = "Clicca sull'email inviata al tuo indirizzo per confermare l'account"
      redirect_to root_url
    else
      msg=@user.errors.full_messages
      flash[:danger]=msg
      redirect_to signup_path
    end
  end
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  #modifica utente
  def update
    @user=User.find(params[:id])
    if @user.update_attributes(user_params)
        flash[:success]="Profile updated"
        redirect_to @user
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    u=User.find(params[:id])
    if currentuser==u || seiadmin
        u.destroy
        flash[:success] = "User deleted"
        redirect_to users_url
    else
        flash[:danger] ="Non puoi cancellare un utente se non sei admin"
        redirect_to root_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless currentuser?(@user)
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    def edit
        @user=User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper


  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_servizi.html.erb
<li id="Servizi-<%= servizi.id %>">
  <span class="nome"><%= link_to servizi.nome, servizi_path(servizi.id)%></span>
  <span class="tipo"><%= servizi.tipo %></span>
  <span class="content"><%= servizi.descrizione %>
  </span>
  <span class="timestamp">
    Creato: <%= time_ago_in_words(servizi.created_at) %> ago.
    <% if currentuser==servizi.user %>
      <%= link_to "Cancella", servizi, :method => :delete,
                                       data: { confirm: "Sicuro?" } %>
    <% end %>
  </span>
</li>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user%>
  <%= link_to user.name, user %>
  <% if currentuser.admin? || currentuser==user %>
    <%= link_to "delete", cancellautente_path(user)  %>
  <% end %>
</li>

app/views/users/edit.html.erb
<head>

  <style>
  
    @import url('https://fonts.googleapis.com/css?family=Merriweather');
    
    
	    h1{
		    color:#B22222;
		    font-family: 'Merriweather', serif;
		  }
	    #div1{
	    font-family: 'Merriweather', serif;
	    width: 500px;
	    margin: left;
	    border: 2px solid black;
	    position: relative;
	    overflow: auto;
	    text-align: left;
	    color: black;
	    padding: 10px 10px;
	    border-radius: 10px 10px 10px 10px;
          }
          #a1{
          font-family: 'Merriweather', serif;
          color: black;
          }
          #change{
	    color:black;
          }
          
         
	 

  </style>

</head>


<body bgcolor='#A9A9A9'>

    <% provide(:title, "Edit user") %>
    <h1>Update your profile</h1>

    <div class="col">
      <div class="col-md-6 col-md-offset-3">
	<%= form_for(@user) do |f| %>
	  
	  <div id='div1' >
	  
	    <a id='a1'><%= f.label :name %></a>
	    <%= f.text_field :name, class: 'form-control' %>
	    <br><br>
	    <a id='a1'><%= f.label :email %></a>
	    <%= f.email_field :email, class: 'form-control' %>
	    <br><br>
	    <a id='a1'><%= f.label :password %></a>
	    <%= f.password_field :password, class: 'form-control' %>
	    <br><br>
	    <a id='a1'><%= f.label :password_confirmation, "Confirmation" %></a>
	    <%= f.password_field :password_confirmation, class: 'form-control' %>
	    <br><br>
	    <%= f.submit  "Save changes", class: "btn btn-primary"%>
	  
	  </div>
	  
	<% end %>

	<div class="gravatar_edit">
	  <%= gravatar_for @user %>
	  <a id='change' href="http://gravatar.com/emails" target=_blank>change</a>
	</div>
      </div>
    </div>
    
    
</body>

app/views/users/index.html.erb
<head>

  <style>
  
      @import url('https://fonts.googleapis.com/css?family=Merriweather');
          h1{
	    color:#B22222;
	    font-family: 'Merriweather', serif; 
          }
          
          #user{
	    font-family: 'Merriweather', serif;
	    color: black;
	    width: 500px;
	    margin: left;
	    border: 2px solid black;
	    position: relative;
	    overflow: auto;
	    text-align: left;
	    padding: 10px 10px;
	    border-radius: 10px 10px 10px 10px;
          }
          
          #nome{
	    font-family: 'Merriweather', serif;
	    color: black;
          }

  
  </style>

</head> 


<body bgcolor='#A9A9A9'>

    <% provide(:title, 'Utenti presenti') %>
    <h1>All users</h1>

    <%= will_paginate %>
    
    <div id='user'>
	<ul class="users">
	  <% @users.each do |user| %>
	      <a id='nome'><%= render user %></a>
	  <% end %>
	</ul>
    </div>
    
    <%= will_paginate %>


</body>

app/views/users/listapreferiti.html.erb
<head>

  <style>
  
      @import url('https://fonts.googleapis.com/css?family=Merriweather');
          h1{
	    color:#B22222;
	    font-family: 'Merriweather', serif; 
          }
           #div02{
	    font-family: 'Merriweather', serif;
	    color:black;
	  }
          
  </style>

</head>

 
<body bgcolor='#A9A9A9'>

    <% provide(:title, 'Lista preferiti') %>
    <h1> Lista preferiti: </h1>
     
	<ul class="preferiti">
	  <% @favorite.each do |s| %>
	    <div id='div02'>
	      <li><%= render s %></li>
	    </div>
	      
	  <% end %>
	</ul>
    

</body>

app/views/users/new.html.erb
<head>
  <style media="screen">
  @import url('https://fonts.googleapis.com/css?family=Merriweather');

    h1{
      text-align: center;
      font-family: 'Merriweather', serif;
      color: black;
    }

    #nome{
      text-align: center;
      font-family: 'Merriweather', serif;
      margin: auto;
      color: black;
    }
    #contenitore{
      background-color:#A9A9A9;
      width:360px;
      height:200px;
      margin:10 auto;
      margin-top:50px;
      text-align:center;
      border: black 2px solid;
      border-radius: 10px 10px 10px 10px;
    }
    #par2{
      text-align: center;
      font-family: 'Merriweather', serif;
      margin: auto;
      color: black;
    }
    #par1{
      text-align: center;
      font-family: 'Merriweather', serif;
      margin: auto;
      color: black;
    }
  </style>
</head>


<body bgcolor="#A9A9A9">
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

    <div id= "contenitore">
      <br />
      <div id = "nome">
      <%= f.label :name %>
      <%= f.text_field :name, id: 'name', class: 'form-control' %>
      <br>
      <br>
      <%= f.label :email %>
      <%= f.text_field :email, id: 'email', class: 'form-control' %>
      <br>
      <br>
      <%= f.label :password %>
      <%= f.password_field :password, id: 'password', class: 'form-control' %>
      <br>
      <br>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, id: 'password_confirmation', class: 'form-control' %>
      <br>
      </div>
    </div>



      <br>
      <div id="par1">
        <center>
          <%= f.submit "Registrati", id: 'registrati', class: "btn btn-primary"  %>
        </center>
      </div>

    <% end %>
    <br />
    <div id="par2">
      <center>
        <p>Gia registrato? <%= link_to "Loggati!", login_path %></p>
      </center>
    </div>

  </div>
</div>
</body>

app/views/users/results.html.erb
<h1>Risultati della ricerca:</h1>

<% if @properties.empty? %>

  <h3>Nessun risultato.</h3>

<% else %>

  <%= form_tag('/welcome/results', method: :get) do %>

    <%= select_tag "ordine", options_for_select([['Titolo', 'title'], ['Prezzo', 'price'], ['Più recenti', 'created_at DESC']]), include_blank: true %>
    <%= hidden_field_tag(:city, @city) %>
    <%= submit_tag("Ordina") %>

  <% end %>

  <p/><%= render 'properties/list' %>

<% end %>

app/views/users/show.html.erb
<head>

  <style>
     @import url('https://fonts.googleapis.com/css?family=Merriweather');
          h1,h3{
          font-family: 'Merriweather', serif;
	    color:#B22222;
          }

           #div01 {
	    font-family: 'Merriweather', serif;
	    width: 500px;
	    margin: left;
	    border: 2px solid black;
	    position: relative;
	    overflow: auto;
	    text-align: left;
	    color:black;
	    padding: 10px 10px;
	    border-radius: 10px 10px 10px 10px;
          }
	  
	  #div02{
	    font-family: 'Merriweather', serif;
	    color:black;
	  }
	  
          a:link {
	    font-family: 'Merriweather', serif;
	    color: black;
          }

  </style>

</head>





<body bgcolor='#A9A9A9'>

      <% provide(:title, @user.name) %>
      <div class="row">
	<aside class="col-md-4">
	  <section class="user_info">
	    <h1>
	      <%= gravatar_for @user %>
	      <%= @user.name %>
	    </h1>
	  </section>
	</aside>
      </div>
      <p id="notice"><%= notice %></p>

      <div id='div01'>

	    <p>
	      <strong>Name:</strong>
	      <%= @user.name %>
	    </p>

	    <p>
	      <strong>Email:</strong>
	      <%= @user.email %>
	    </p>

      </div>

      <br><br>

      <div class="col-md-8">
	  <% if @user.servizis.any? %>
	    <h3>Numero Servizi: (<%= @user.servizis.count %>)</h3>
	    <ol class="servizi">
	      <div id='div02'>
	      <li><%= render @user.servizis %></li>
	      </div>
	    </ol>
	    <%= will_paginate @servizi %>
	  <% end %>
	</div>

     <%= link_to 'Edit', edit_user_path(@user) %>
     <%= link_to 'Home Utente', root_path %>
     <%= link_to 'Logout', esci_path %>

</body>